---
abstract: 'non-blocking system DNS resolver'
author:
  - 'Oleg G <oleg@cpan.org>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-DNS-Native
no_index:
  directory:
    - t
    - inc
requires:
  Socket: '1.95'
resources:
  repository: https://github.com/olegwtf/p5-Net-DNS-Native
version: '0.02'
